defaults: &defaults
  google_oAuth:
    api_key: '505150086257-b713gglc7cbhussjdtih591ucqgptprp.apps.googleusercontent.com'
    api_secret: 's7lKrrP9cQ6zInw8zeHng6s2'

development:
  <<: *defaults

test:
  <<: *defaults

producion:
  google_oAuth:
    api_key: '505150086257-jmhnraghosdeaq8aum31bhhfqb2qmae0.apps.googleusercontent.com'
    api_secret: 'TvzlFh2x3EaLfETTpnZ4Pl95'
  instagram_oAuth:
    api_key: '1e595466ab8a4671a4210d974b5008bf'
    api_secret: '14eed34d8a9244338c6fb85d308e0be5'
  twitter_oAuth:
    api_key: '7AnydeAscaWXICHZ5qUkq35Vf'
    api_secret: 'GqPPSNqCgZXQuBf962XKaaijawifMlz7X7bWDI6OWSZFax8Z9k'
  facebook_oAuth:
    api_key: '142528229808784'
    api_secret: 'a85b8e4107bd9f083a754d08feb18fee'
